# Generated by Django 4.2.7 on 2025-09-18 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Amount in paise')),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed')], default='created', max_length=16)),
                ('razorpay_order_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=128)),
                ('razorpay_signature', models.CharField(blank=True, max_length=256)),
                ('receipt', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
