# Generated by Django 4.2.11 on 2025-09-18 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('welcome_message', models.CharField(default='Hi! How can I help you today?', max_length=255)),
                ('primary_color', models.CharField(default='#4F46E5', max_length=7)),
                ('position', models.CharField(choices=[('bottom-right', 'Bottom Right'), ('bottom-left', 'Bottom Left')], default='bottom-right', max_length=20)),
                ('system_prompt', models.TextField(default='You are a helpful assistant for this website. Answer concisely and helpfully.')),
                ('model_name', models.CharField(default='llama3-8b-8192', max_length=100)),
                ('temperature', models.FloatField(default=0.4)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
